### ISSUE TITLE
Error when compiling wwith SWIG

### ISSUE THREAD

**Issue by mahynski** [hhatch/feasst#4]
Not sure if this is a SWIG problem, conda problem, or feasst problem but I just updated the feasst version I have on my Ubuntu 18.04 lTS workstation and tried to compile with -DUSE_SWIG=ON as described in the instructions.  Seems to work but I did get a warning during install:

/home/nam4/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: The version specified ('v0.15.0-1-ga85da90992') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

Anyway, I compiled (in python 3 environment) and got this error when I tried to import into a jupyter notebook:

ImportError                               Traceback (most recent call last)
~/anaconda3/envs/py37/lib/python3.7/site-packages/feasst-v0.12.0_33_g3bb7454cb6-py3.7.egg/feasst.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

~/anaconda3/envs/py37/lib/python3.7/importlib/__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

~/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

~/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

~/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py in module_from_spec(spec)

~/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap_external.py in create_module(self, spec)

~/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: /home/nam4/anaconda3/envs/py37/lib/python3.7/site-packages/feasst-v0.12.0_33_g3bb7454cb6-py3.7.egg/_feasst.so: undefined symbol: _ZTIN6feasst14TrialTranslateE

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-4bf49f3be85b> in <module>
----> 1 import feasst as fst
      2 import pyfeasst

~/anaconda3/envs/py37/lib/python3.7/site-packages/feasst-v0.12.0_33_g3bb7454cb6-py3.7.egg/feasst.py in <module>
     15         except ImportError:
     16             return importlib.import_module('_feasst')
---> 17     _feasst = swig_import_helper()
     18     del swig_import_helper
     19 elif _swig_python_version_info >= (2, 6, 0):

~/anaconda3/envs/py37/lib/python3.7/site-packages/feasst-v0.12.0_33_g3bb7454cb6-py3.7.egg/feasst.py in swig_import_helper()
     14             return importlib.import_module(mname)
     15         except ImportError:
---> 16             return importlib.import_module('_feasst')
     17     _feasst = swig_import_helper()
     18     del swig_import_helper

~/anaconda3/envs/py37/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ImportError: /home/nam4/anaconda3/envs/py37/lib/python3.7/site-packages/feasst-v0.12.0_33_g3bb7454cb6-py3.7.egg/_feasst.so: undefined symbol: _ZTIN6feasst14TrialTranslateE

Looks to me like something relateed to TrialTranslate.  I got this error from the hwh/acc branch first, but also after switching to main and deleting the build/ directory.  Can you reproduce this error or is something on my machine?  BTW swig version is 3.0.12 if that matters.

**Comment by hhatch** [comment]
It seems python is picking up an old install of feasst, e.g., "ImportError: /home/nam4/anaconda3/envs/py37/lib/python3.7/site-packages/feasst-v0.12.0_33" references v0.12 while main is on v0.15. Did you also "make install"? If so, try removing all /anaconda3/envs/py37/lib/python3.7/site-packages/feasst* and rebuilding

**Comment by mahynski** [comment]
That helped, but now I am getting:

what():  Throw on proc 0 : # Assertion `version == 692` failed0 plugin/configuration/src/particle_factory.cpp:222: unrecognized version: 847

Aborted (core dumped)

**Comment by hhatch** [comment]
That error happens when something goes wrong when attempting to deserialize. My guess is that the new version is trying to read a checkpoint generated by an older version.

**Comment by mahynski** [comment]
I might be on the wrong branch... let me try that again

**Comment by mahynski** [comment]
ok nvm, turns out I was reading results of an old simulation...  the other issues were resolved after specifiying the -DPYTHON_LIBRARY correctly when compiling
